// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// SysParamDao is the manager for logic model data accessing and custom defined data operations functions management.
type SysParamDao struct {
	Table   string          // Table is the underlying table name of the DAO.
	Group   string          // Group is the database configuration group name of current DAO.
	Columns SysParamColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// SysParamColumns defines and stores column names for table sys_param.
type SysParamColumns struct {
	ParamId    string // 参数配置id
	ParamName  string // 参数名称
	ParamKey   string // 参数键名
	ParamValue string // 参数值
	ParamType  string // 参数类型: 1系统内置 2非系统内置参数
	Remark     string // 备注信息
	CreateBy   string // 创建者
	CreateTime string // 创建时间
	UpdateBy   string // 更新者
	UpdateTime string // 更新时间
}

//  sysParamColumns holds the columns for table sys_param.
var sysParamColumns = SysParamColumns{
	ParamId:    "param_id",
	ParamName:  "param_name",
	ParamKey:   "param_key",
	ParamValue: "param_value",
	ParamType:  "param_type",
	Remark:     "remark",
	CreateBy:   "create_by",
	CreateTime: "create_time",
	UpdateBy:   "update_by",
	UpdateTime: "update_time",
}

// NewSysParamDao creates and returns a new DAO object for table data access.
func NewSysParamDao() *SysParamDao {
	return &SysParamDao{
		Group:   "default",
		Table:   "sys_param",
		Columns: sysParamColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysParamDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysParamDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysParamDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
