// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// SysMenuDao is the manager for logic model data accessing and custom defined data operations functions management.
type SysMenuDao struct {
	Table   string         // Table is the underlying table name of the DAO.
	Group   string         // Group is the database configuration group name of current DAO.
	Columns SysMenuColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// SysMenuColumns defines and stores column names for table sys_menu.
type SysMenuColumns struct {
	Id            string // 菜单id
	Pid           string // 父菜单id
	Title         string // 菜单标题
	TitleTag      string // 菜单标签
	Type          string // 菜单类型(0目录 1菜单 2按钮)
	Component     string // 前端组件路径
	Icon          string // 菜单图标
	Router        string // 后端路由规则
	RestInterface string // 请求接口,一个菜单功能项可对应多个接口,多个接口 | 分隔
	Weigh         string // 菜单权重(菜单显示顺序)
	IsHide        string // 是否隐藏: 0不隐藏 1隐藏
	Remark        string // 备注
	CreateBy      string // 创建者
	CreateTime    string // 创建时间
	UpdateBy      string // 更新者
	UpdateTime    string // 更新时间
}

//  sysMenuColumns holds the columns for table sys_menu.
var sysMenuColumns = SysMenuColumns{
	Id:            "id",
	Pid:           "pid",
	Title:         "title",
	TitleTag:      "title_tag",
	Type:          "type",
	Component:     "component",
	Icon:          "icon",
	Router:        "router",
	RestInterface: "rest_interface",
	Weigh:         "weigh",
	IsHide:        "is_hide",
	Remark:        "remark",
	CreateBy:      "create_by",
	CreateTime:    "create_time",
	UpdateBy:      "update_by",
	UpdateTime:    "update_time",
}

// NewSysMenuDao creates and returns a new DAO object for table data access.
func NewSysMenuDao() *SysMenuDao {
	return &SysMenuDao{
		Group:   "default",
		Table:   "sys_menu",
		Columns: sysMenuColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysMenuDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysMenuDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysMenuDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
