// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// SysUserDao is the manager for logic model data accessing and custom defined data operations functions management.
type SysUserDao struct {
	Table   string         // Table is the underlying table name of the DAO.
	Group   string         // Group is the database configuration group name of current DAO.
	Columns SysUserColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// SysUserColumns defines and stores column names for table sys_user.
type SysUserColumns struct {
	UserId      string // 用户id
	LoginName   string // 登录账号
	UserName    string // 用户昵称
	UserType    string // 用户类型(0系统管理员 1管理员 2操作员)|20221020实现角色管理功能废弃
	Email       string // 用户邮箱
	PhoneNumber string // 手机号码
	Sex         string // 用户性别(0保密 1男 2女)
	Avatar      string // 头像路径
	Password    string // 密码
	Salt        string // 加密盐
	Status      string // 帐号状态（0正常 1停用 2未验证）
	LoginIp     string // 最后登陆ip
	LoginDate   string // 最后登陆时间
	Remark      string // 备注信息
	CreateBy    string // 创建者
	CreateTime  string // 创建时间
	UpdateBy    string // 更新者
	UpdateTime  string // 更新时间
}

//  sysUserColumns holds the columns for table sys_user.
var sysUserColumns = SysUserColumns{
	UserId:      "user_id",
	LoginName:   "login_name",
	UserName:    "user_name",
	UserType:    "user_type",
	Email:       "email",
	PhoneNumber: "phone_number",
	Sex:         "sex",
	Avatar:      "avatar",
	Password:    "password",
	Salt:        "salt",
	Status:      "status",
	LoginIp:     "login_ip",
	LoginDate:   "login_date",
	Remark:      "remark",
	CreateBy:    "create_by",
	CreateTime:  "create_time",
	UpdateBy:    "update_by",
	UpdateTime:  "update_time",
}

// NewSysUserDao creates and returns a new DAO object for table data access.
func NewSysUserDao() *SysUserDao {
	return &SysUserDao{
		Group:   "default",
		Table:   "sys_user",
		Columns: sysUserColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysUserDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysUserDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysUserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
