// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// SysBlackListDao is the manager for logic model data accessing and custom defined data operations functions management.
type SysBlackListDao struct {
	Table   string              // Table is the underlying table name of the DAO.
	Group   string              // Group is the database configuration group name of current DAO.
	Columns SysBlackListColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// SysBlackListColumns defines and stores column names for table sys_black_list.
type SysBlackListColumns struct {
	Id         string // 配置ID
	Type       string // 1黑名单 2白名单
	IpAddr     string // 访问IP地址
	CreateBy   string // 创建者
	CreateTime string // 创建时间
	UpdateBy   string // 更新者
	UpdateTime string // 更新时间
}

//  sysBlackListColumns holds the columns for table sys_black_list.
var sysBlackListColumns = SysBlackListColumns{
	Id:         "id",
	Type:       "type",
	IpAddr:     "ip_addr",
	CreateBy:   "create_by",
	CreateTime: "create_time",
	UpdateBy:   "update_by",
	UpdateTime: "update_time",
}

// NewSysBlackListDao creates and returns a new DAO object for table data access.
func NewSysBlackListDao() *SysBlackListDao {
	return &SysBlackListDao{
		Group:   "default",
		Table:   "sys_black_list",
		Columns: sysBlackListColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysBlackListDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysBlackListDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysBlackListDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
