// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gowebserver/app/system/dao/internal"
)

// sysParamDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type sysParamDao struct {
	*internal.SysParamDao
}

var (
	// SysParam is globally public accessible object for table sys_param operations.
	SysParam = sysParamDao{
		internal.NewSysParamDao(),
	}
)

// Fill with you ideas below.
