// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gowebserver/app/system/dao/internal"
)

// sysOperLogDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type sysOperLogDao struct {
	*internal.SysOperLogDao
}

var (
	// SysOperLog is globally public accessible object for table sys_oper_log operations.
	SysOperLog = sysOperLogDao{
		internal.NewSysOperLogDao(),
	}
)

// Fill with you ideas below.
