// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gowebserver/app/system/dao/internal"
)

// sysUserOnlineDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type sysUserOnlineDao struct {
	*internal.SysUserOnlineDao
}

var (
	// SysUserOnline is globally public accessible object for table sys_user_online operations.
	SysUserOnline = sysUserOnlineDao{
		internal.NewSysUserOnlineDao(),
	}
)

// Fill with you ideas below.
