// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

// CasbinRuleForDao is the golang structure of table casbin_rule for DAO operations like Where/Data.
type CasbinRuleForDao struct {
	Ptype interface{} `orm:"ptype"` //
	V0    interface{} `orm:"v0"`    //
	V1    interface{} `orm:"v1"`    //
	V2    interface{} `orm:"v2"`    //
	V3    interface{} `orm:"v3"`    //
	V4    interface{} `orm:"v4"`    //
	V5    interface{} `orm:"v5"`    //
}
