// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

// CasbinRule is the golang structure for table casbin_rule.
type CasbinRule struct {
	Ptype string `orm:"ptype" json:"ptype" description:""`
	V0    string `orm:"v0"    json:"v0"    description:""`
	V1    string `orm:"v1"    json:"v1"    description:""`
	V2    string `orm:"v2"    json:"v2"    description:""`
	V3    string `orm:"v3"    json:"v3"    description:""`
	V4    string `orm:"v4"    json:"v4"    description:""`
	V5    string `orm:"v5"    json:"v5"    description:""`
}
